project_id = "woucixqbnzmvlvnaaelb"

[functions.create-livepeer-stream]
verify_jwt = true

[functions.livepeer-stream]
verify_jwt = true

[functions.livepeer-pull-stream]
verify_jwt = true

[functions.livepeer-transcode]
verify_jwt = true

[functions.storj-upload]
verify_jwt = true

[functions.livepeer-webhook]
verify_jwt = false

[functions.livepeer-playback]
verify_jwt = false

[functions.livekit-webhook]
verify_jwt = false

[functions.livekit-egress]
verify_jwt = true

[functions.save-to-storj]
verify_jwt = true

[functions.youtube-oauth]
verify_jwt = false

[functions.youtube-streams]
verify_jwt = true

[functions.livepeer-multistream]
verify_jwt = true

[functions.livepeer-clip]
verify_jwt = true

[functions.process-tip]
verify_jwt = false